### ISSUE TITLE
Missed Functionality and other bugs

### ISSUE THREAD

**Issue by Jagadesh-Ram** [khusharth/gitpedia#2]
After entering a wrong user name there is no way to back to main menu to search again.
Suggested fix:

- [x] Add a href attribute to the logo of gitpedia.
- [x] Add a go back button to replicate the above action.

Miscellaneous bugs:

- [x] Never console.log for key indicators! 
- [x] Recommended to add a toast for indicating there is no search tag present upon clicking the search icon.

**Comment by Jagadesh-Ram** [comment]
Great! prompting the user with pop up telling the user field is blank is what i intend to mention!...

**Comment by Jagadesh-Ram** [comment]
Also include a License file...This may have a potential to become a viable product of some kind in evaluating candidates in a interview! #justsaying

**Comment by khusharth** [comment]
@Jagadesh-Ram Thank a lot for explaining i will work on it. :+1:

**Comment by jasbindar-singh** [comment]
hey, adding one more thing, when the page loads the chart's animation are triggered without being noticed, you could add a trigger when the charts are in the user's viewing viewport would be better. You can use inspection observer API

**Comment by khusharth** [comment]
@jasbindar-singh I will check that out. Thanks for the suggestion :)
